AS		:= as --32
CC		:= gcc -pipe
AR		:= ar
LD		:= ld
OBJDUMP	:= objdump

CFLAGS	:= -nostdinc -O1 -MD -m32 -std=gnu99 -fno-builtin -fno-omit-frame-pointer -Wno-format -Wall -Wno-unused -Werror -g0
LDFLAGS	:= -m elf_i386 -nostdlib
