AS		:= as --32
CC		:= gcc -pipe
AR		:= ar
LD		:= ld
OBJDUMP	:= objdump

CFLAGS	:= -nostdinc -O1 -MD -m32 -std=gnu99 -fno-builtin -fno-omit-frame-pointer -fno-stack-protector -fno-pie -Wno-format -Wall -Werror -Wempty-body -Wno-unused -Werror -ggdb
LDFLAGS	:= -m elf_i386 -nostdlib
